### ISSUE TITLE
Docs website is down

### ISSUE THREAD

**Issue by jlarmstrongiv** [udecode/zustood#26]
**Description**

The docs website is down! 😱

**Steps**

1. Go to 'https://zustood.udecode.io/' 🌐
2. See error 🚨 --> Not Found - Request ID: 01FRVT1XAXWCZH55H713WXBSFC

**Expectation**

A docs website 😇📚

**Comment by zbeyens** [comment]
Thanks for the issue! Fixed by using https://zustood.netlify.app
