### ISSUE TITLE
API documentation site is not available

### ISSUE THREAD

**Issue by andreifloricel** [udecode/zustood#55]
The API docs site is currently not available: https://zustood.udecode.io/

<img width="597" alt="image" src="https://user-images.githubusercontent.com/5867129/229086623-405d9184-67c7-4f66-b194-8102915b7fcc.png">

**Comment by zbeyens** [comment]
Thanks for the issue, fixed now.

**Comment by vcardins** [comment]
The API document page is  not available.

**Comment by zbeyens** [comment]
Updated the link

**Comment by vijayRT** [comment]
Seems like it's unavailable again 
<img width="467" alt="image" src="https://github.com/user-attachments/assets/a54a7eb7-f494-4ce2-b189-c60cb6d1994a">
